import Head from 'next/head';
import Image from 'next/image';
import { DetailedHTMLProps } from 'react';
import PokeDex from "@/data/pokedex.json";
import { useState, useEffect } from 'react';

export default function Home() {

  const [Generation, setGeneration] = useState();
  const [Mega, setMega] = useState(false);
  const [CopyPokeDex, setPokedex] = useState([] as any);

  function FilterPokeDex() {
    let pokedex: any = [];
    PokeDex.filter((pokemon: any, i) => {
      if (pokemon.is_default) {
        pokedex.push({ ...pokemon })
      }
    })

    setPokedex(pokedex);
  }

  useEffect(() => {
    FilterPokeDex()
  }, [])

  return (
    <>
      <Head>
        <title>Guess The Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <>
          <h1 className='font-bold text-2xl'>Guess the Pokemon!</h1>

          {CopyPokeDex && CopyPokeDex.map((pokemon: any, i: number) => (
            <div key={i}>
              <h2>{pokemon.pokemon_name}</h2>
              {pokemon.pokemon_name.includes(' ') ? <Image src={`/pokemon/${pokemon.pokemon_name.toLowerCase().replace(/ /g,"_")}.png`} alt={pokemon.pokemon_name} width={150} height={150} /> : <Image src={`/pokemon/${pokemon.pokemon_name.toLowerCase()}.png`} alt={pokemon.pokemon_name} width={150} height={150} /> }
            </div>
          ))
          }
        </>
      </main>
    </>
  )
}
